### ISSUE TITLE
Raspberry Zero W gets stuck after hotword

### ISSUE THREAD

**Issue by jbrepogmailcom** [shivasiddharth/GassistPi#688] opened 2018-12-13 16:47 UTC
Hello. When running pushbutton.py, I get some error messages, but the script stops and waits for a hotword. After saying alexa few times it seems to get stuck and do not respond to anything. Is there anything I can do?

[01939a08] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[019452a0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
USB-DAC
Initializing GPIOs 5 and 6 for assistant activity indication
INFO:snowboy:Keyword 1 detected at time: 2018-12-13 16:43:07
WARNING:root:SoundDeviceStream read overflow (3200, 6400)
INFO:snowboy:Keyword 1 detected at time: 2018-12-13 16:43:35
WARNING:root:SoundDeviceStream read overflow (3200, 6400)

**Comment by shivasiddharth** [comment] 2018-12-13 17:47
Duplicate of #622 .

**Closed by shivasiddharth** 2018-12-13 17:47 UTC
