### ISSUE TITLE
Download issue  

### ISSUE THREAD

**Issue by aburaihanshawon** [shivasiddharth/GassistPi#734] opened 2019-01-12 04:41 UTC
When i execute the last command and enter my project id,model id it starts to download some file.at this time in a certain step it stop downloading forever and never goes to next step to download or install file.the last line like this "Running setup.py bdist_wheel for lxml...." what is the solution.

**Comment by shivasiddharth** [comment] 2019-01-12 10:38
Duplicate of #728

**Closed by shivasiddharth** 2019-01-12 10:38 UTC

**Comment by piyushtanksale00** [comment] 2019-02-03 15:01
When i run update.sh script it is showing project already up to date but files are not updated. config.yaml file is not showing update of  feb 3 2019

**Comment by shivasiddharth** [comment] 2019-02-03 15:18
Not sure when you cloned the git. get the latest update script from master.

**Comment by shivasiddharth** [comment] 2019-02-03 15:59
I have checked the update script multiple times and it works. Make sure to use them properly. Pull the latest update script and replace the old one that you have got. It has to be in the /scripts directory.
