### ISSUE TITLE
ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by Krato5** [shivasiddharth/GassistPi#235] opened 2018-02-27 10:13 UTC
/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --project_id 'xxxxxxxxxxxx'  --device_model_id 'xxxxxxxxxx'
device_model_id: xxxxxxxxxxx
device_id: xxxxxxxxxxxxxxxxxxxxxxxx

https://embeddedassistant.googleapis.com/v1alpha2/projects/replxxxxxxxxxx/devices/C15xxxxxxxxxxE92DE6AAECB201629B23E1 403
ON_MUTED_CHANGED:
  {'is_muted': False}
ON_START_FINISHED
[7418:7441:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with                                                     given CA certificates
[7418:7441:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with                                                     given CA certificates
[7418:7441:ERROR:assistant_nupnp_client.cc(103)] Cloud discovery nupnp request failed: [60] Peer certificate cannot be authenticated with                                                     given CA certificates

**Comment by shivasiddharth** [comment] 2018-02-27 11:00
Duplicate of #234

**Closed by shivasiddharth** 2018-02-27 11:00 UTC
