### ISSUE TITLE
GassistPi and 3.5 LCD

### ISSUE THREAD

**Issue by chathurangawijetunge** [shivasiddharth/GassistPi#319] opened 2018-04-25 05:30 UTC
I have your GassistPi working will.
And I have 3.5 LCD also working.
But as soon as I started the assistant the lcd goes out. (When assistant virtual environment starts LCD goes wite)
Why...?
How to fix this...?

**Comment by shivasiddharth** [comment] 2018-04-25 08:32
Duplicate of #227

**Closed by shivasiddharth** 2018-04-25 08:32 UTC
