### ISSUE TITLE
Error first start assistant

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#661] opened 2018-11-30 04:38 UTC
nnection refused
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 44, in <module>
    from actions import say
  File "/home/pi/GassistPi/src/actions.py", line 191, in <module>
    translator = Translator()
NameError: name 'Translator' is not defined

**Comment by shivasiddharth** [comment] 2018-11-30 06:35
Duplicate of #658

**Closed by shivasiddharth** 2018-11-30 06:35 UTC
