### ISSUE TITLE
low volume

### ISSUE THREAD

**Issue by rottieGO** [shivasiddharth/GassistPi#168] opened 2018-01-29 14:33 UTC
Hi, I am using your USB microphone / Audio Jack script.  The "ding" after OK GOOGLE is loud but the actual voice is super low.  The Pi volume is at its max as is my powered speaker in order to hear anything.  This wasn't an issue with older release of gassistpi

**Comment by shivasiddharth** [comment] 2018-01-29 14:38
Issue duplicate of #133

**Closed by shivasiddharth** 2018-01-29 14:38 UTC
Labels: duplicate
