### ISSUE TITLE
The Google assistant output volume

### ISSUE THREAD

**Issue by dhruvwagh** [shivasiddharth/GassistPi#198] opened 2018-02-10 14:54 UTC
The output volume of the Google assistant is very low and noisy. The audio from my rpi3 is on full volume and my speakers volume is also max.
I tried searching the scripts and tinkering with alsa mixer fyi but no results please help..

**Comment by shivasiddharth** [comment] 2018-02-10 14:59
Before opening an issue, i would suggest you to go through or search for related issues already open/closed. 
Duplicate of #133

**Closed by shivasiddharth** 2018-02-10 14:59 UTC
