### ISSUE TITLE
RPI crashes when I ask to youtube "stream XYZ"

### ISSUE THREAD

**Issue by kg123456** [shivasiddharth/GassistPi#557] opened 2018-10-04 08:23 UTC
Hi
Nice work on Gassist.
Got Google assistant running but when I try to stream youtube song or Radio 2, system hangs with excerpt below:

ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "stream I got you"}
stopping vlc
ERROR:__main__:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/actions.py", line 1008, in YouTube_No_Autoplay
    say("Getting youtube link")
  File "/home/pi/GassistPi/src/actions.py", line 209, in say
    words= translator.translate(words, dest=language)

Any advice appreciated.
```


### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

## If answer to question 2 is No, then proceed further.
### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

## If answer to question 4 is No, then proceed further.
### Manually start the assistant. For guidelines to start the assistant manually refer [this](https://github.com/shivasiddharth/GassistPi#manually-start-the-assistant)

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

### Attach the log file. Log file can be found in /tmp directory. Remeber to copy your log file before shutting down or restarting the Pi.

**Comment by shivasiddharth** [comment] 2018-10-04 10:50
The error that you have posted is only a part of the entire error message that you get. Duplicate of #534

**Closed by shivasiddharth** 2018-10-04 10:50 UTC
