### ISSUE TITLE
gassistpi wont read nodemcu crashes after speach

### ISSUE THREAD

**Issue by ykr412** [shivasiddharth/GassistPi#679] opened 2018-12-08 19:03 UTC
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "wireless turn device on"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "wireless turn device on"}
ERROR:__main__:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 692, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 557, in main
    ESP(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 293, in ESP
    say("Turning On " + name)
  File "/home/pi/GassistPi/src/actions.py", line 227, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 218, in trans
    transword= translator.translate(words, dest=lang)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by shivasiddharth** [comment] 2018-12-08 19:42
Duplicate of #534

**Closed by shivasiddharth** 2018-12-08 19:42 UTC
