### ISSUE TITLE
How to setup GassistPi for PHILIPS HUE lights

### ISSUE THREAD

**Issue by aro28** [shivasiddharth/GassistPi#390] opened 2018-06-10 18:22 UTC
Hi everyone!
At this moment i have Philips Hue Smart bridge with Smart bulbs and it works and i can remote them thru my iPhone device.
I've read Read.md file on "EMULATED PHILIPS HUE SERVICE AND CONTROL" section (step 19) and i can not understand clearly how to setup it.

Should i use NodeMCU devices for controlling my Hue lights? I never used and work with that type of devices. If yes, i would be appreciate if you could me please send me a proper link for guideline.
Many thanks for your great work and efforts.
Best,
aro28

**Comment by shivasiddharth** [comment] 2018-06-10 18:55
Duplicate of #387

**Closed by shivasiddharth** 2018-06-10 18:55 UTC
