### ISSUE TITLE
Where do I link my Google Home Pi to my Home App?

### ISSUE THREAD

**Issue by GoNovaVFX** [shivasiddharth/GassistPi#275] opened 2018-03-18 15:44 UTC
I've already read previous issue's and I meet the criteria. My device is running on Android 7.0, the language is set to English US and both my Android Device and RPi are connected to the same wifi network.

I'm running an RPi 2B and I'm trying to connect it to the home app, but where do I even start linking it? When I click on add device I just see a bunch of random products like Philips hue etc.

**Comment by shivasiddharth** [comment] 2018-03-18 16:39
Duplicate of #202

**Closed by shivasiddharth** 2018-03-18 16:39 UTC
