### ISSUE TITLE
None of the features are working

### ISSUE THREAD

**Issue by majorroli** [shivasiddharth/GassistPi#637] opened 2018-11-19 17:55 UTC
### Describe the bug:
```
I have followed the instructions and got your project working in a way that the sound is working and Google Assistant is answering questions like "Hey Google, how are you".
But none of the features are working. I left the config.yaml as it was to first try out the custom questions": Hey Google, how are you" or "Hey Google, play Radio one" They all return with the following error

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
Yes

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```
device_model_id: tacteam-222322-tacteam-ouwe93
device_id: E0EF8F1BD91AE0B6DF3F8DE4C77CA9F0

ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED
ON_START_FINISHED
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_FINISHED
ON_RESPONDING_FINISHED
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ERROR:__main__:name 'Keyerror' is not defined
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 470, in main
    say(selectedans[0])
  File "/home/pi/GassistPi/src/actions.py", line 219, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 210, in trans
    transword= translator.translate(words, dest=lang)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 673, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 472, in main
    except Keyerror:
NameError: name 'Keyerror' is not defined

```

### Paste the contents of the terminal below
```
device_model_id: tacteam-222322-tacteam-ouwe93
device_id: E0EF8F1BD91AE0B6DF3F8DE4C77CA9F0

ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED
ON_START_FINISHED
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_FINISHED
ON_RESPONDING_FINISHED
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ERROR:__main__:name 'Keyerror' is not defined
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 470, in main
    say(selectedans[0])
  File "/home/pi/GassistPi/src/actions.py", line 219, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 210, in trans
    transword= translator.translate(words, dest=lang)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 673, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 472, in main
    except Keyerror:
NameError: name 'Keyerror' is not defined


```

device_model_id: tacteam-222322-tacteam-ouwe93
device_id: E0EF8F1BD91AE0B6DF3F8DE4C77CA9F0

ON_MUTED_CHANGED:
  {"is_muted": false}
ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED
ON_START_FINISHED
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "how are you"}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_FINISHED
ON_RESPONDING_FINISHED
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_RENDER_RESPONSE:
{
  "text": "I'm doing great, thanks for asking. What can I help you with?",
  "type": 0
}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": true}
ON_CONVERSATION_TURN_STARTED

ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "hey Google who are you"}
ERROR:__main__:name 'Keyerror' is not defined
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 470, in main
    say(selectedans[0])
  File "/home/pi/GassistPi/src/actions.py", line 219, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 210, in trans
    transword= translator.translate(words, dest=lang)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 673, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 472, in main
    except Keyerror:
NameError: name 'Keyerror' is not defined

#No GassistPi log file found ?!

**Comment by shivasiddharth** [comment] 2018-11-19 18:06
> Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
> Yes

Duplicate of #534

**Closed by shivasiddharth** 2018-11-19 18:06 UTC
