### ISSUE TITLE
custom command "shut down" not working

### ISSUE THREAD

**Issue by Gretehuber** [shivasiddharth/GassistPi#251] opened 2018-03-05 14:47 UTC
Hi,

thanks for this great work! 
It seems that the custom/local commands like "shut down" do not work. I guess main.py uses actions.py. In there is a check for the key words "shut down" but this doens't seem to work. Any idea how I can track down the problem?

Thanks, Gitti

**Comment by Rooster69** [comment] 2018-03-05 16:26
Try "hey google trigger shutdown" The key word is **trigger**

**Comment by Wim3d** [comment] 2018-03-11 20:47
I have the same issue. Google Assistant works fine, but not the local commands like shutdown. It seems like "trigger" does not trigger on my Pi.

**Comment by shivasiddharth** [comment] 2018-03-15 17:56
Duplicate of #199

**Closed by shivasiddharth** 2018-03-15 17:56 UTC

**Comment by DerakuAng28** [comment] 2018-03-16 17:03
This may be silly but I think I figured it out. The code wrote "shut down" with a space in between but Google Assistant parsed it as a single word "shutdown". It works for me after changing the code to "shutdown". Hope this helps.
