### ISSUE TITLE
Problem Running Assistant

### ISSUE THREAD

**Issue by pgs32** [shivasiddharth/GassistPi#451] opened 2018-07-24 16:54 UTC
Hi

I am very new to the Pi and I have tried to install the Google Assistant as per your instruction on a Pi 2 at https://github.com/shivasiddharth/GassistPi

For your information I am running the latest version of stretch, and I have a USB microphone and a speaker connected to the 3.5mm  socket.

I can manually start the assistant and it responds to the wake word, however when I ask a question it consistently replies _"something went wrong, wait a few seconds" or "there is a glitch, try again in a few seconds"

Suggesting that the speaker, microphone and at least in part Google assistant are working.

I am getting am error in the terminal window stating PulseAudio server connection failure: connection refused.

I have also included the last few lines from the terminal window showing a further main.py error

_### 

> SA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50                                                                                                                           
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround51.0:CARD=0'                                                                             
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51                                                                                                                           
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.surround71.0:CARD=0'                                                                             
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71                                                                                                                           
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'                                                   
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958                                                                                                                               
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'                                                   
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif                                                                                                                                
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'                                                   
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory                                                                                                           
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif                                                                                                                                
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi                                                                                                                       
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi                                                                                                                       
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem                                                                                                                      
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem                                                                                                                      
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline                                                                                                                  
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline                                                                                                                  
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'                                                                                               
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory                                                                                                      
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa                                                                                                                             
> ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'                                                                                               
> ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                                
> ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory                                                                                                      
> ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa                                                                                                                             
> ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream                                                                                               
> Cannot connect to server socket err = No such file or directory                                                                                                                              
> Cannot connect to server request channel                                                                                                                                                     
> jack server is not running or cannot be started                                                                                                                                              
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock                                                                                                            
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock                                                                                                            
> usage: main.py [-h] [--device-model-id DEVICE_MODEL_ID]                                                                                                                                      
>                [--project-id PROJECT_ID] [--device-config DEVICE_CONFIG_FILE]                                                                                                                
>                [--credentials OAUTH2_CREDENTIALS_FILE] [-v]                                                                                                                                  
> main.py: error: unrecognized arguments: --assistant-6459a-assistant-m4mdvn

I would like to thank you for al of your efforts and would be very grateful if you could point me in the right direction.
_

**Comment by shivasiddharth** [comment] 2018-07-24 16:59
Duplicate of #450

**Closed by shivasiddharth** 2018-07-24 16:59 UTC
