### ISSUE TITLE
google assistant using raspberry pi 3

### ISSUE THREAD

**Issue by praveen04n** [shivasiddharth/GassistPi#426] opened 2018-07-02 06:38 UTC
### Describe the bug:
hi sir my google assistant is working properly only for  4 to 5 questions and after  it is getting off , i have to restart it again. please help me to work continuously till i off.

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues). 
Yes
### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes
### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment] 2018-07-02 08:42
Duplicate of #425 . Again Issue template not used properly. Please don't spam with duplicate improper  issue repostings.

**Closed by shivasiddharth** 2018-07-02 08:42 UTC
