### ISSUE TITLE
ERROR: gassist-installer-pi3.sh: line 54:  7462 Segmentation fault

### ISSUE THREAD

**Issue by madmadda** [shivasiddharth/GassistPi#392] opened 2018-06-14 17:38 UTC
I have done every single step and i get this while i run the gassist-installer-pi3.sh script `error message /home/pi/GassistPi/scripts/gassist-installer-pi3.sh: line 54:  7462 Segmentation fault      googlesamples-assistant-hotword --project_id $projid --device_model_id $modelid`
I cant even complete authorication ok message

and when i start the service.sh i talk to her and she reply ''something went wrong try again in a few sconds''(also i get a message above her, that my device is not register, but i register it in the cloud google so why?).
for some reason its not working
whats happening?
NOTE: I have done everything, from creating console.action registering in gui everything, downloading the json. but the error keep hitting, its like something is wrong in the implementation of the code.

**Comment by shivasiddharth** [comment] 2018-06-14 18:40
Closing this for following reasons.
1. Issue does not use/follow the issue template.
2. Duplicate of #369
3. All of your above mentioned queries have been discussed in one or more of the other issues. Please spend time searching through the issues.

**Closed by shivasiddharth** 2018-06-14 18:40 UTC
