### ISSUE TITLE
snowboy

### ISSUE THREAD

**Issue by karrarmaher** [shivasiddharth/GassistPi#281] opened 2018-03-21 20:17 UTC
What about the  Multiple Custom Wakeword Triggers for Headless Google Assistant﻿?

**Comment by rammere** [comment] 2018-03-22 08:29
I can not see snowboy script where it is ?

**Comment by codelock13** [comment] 2018-03-22 08:42
Please other posts the repo owner clearly said it is coming in next update
as it was not working properly with new SDK if you have fix to it please
pull request

**Comment by rammere** [comment] 2018-03-22 09:13
Hi Sorry I did not notice that , though it will be better to be mentioned in the Documentation ,anyway I will try to find a solution .
:)

**Comment by shivasiddharth** [comment] 2018-03-22 09:36
Duplicate of #136

**Closed by shivasiddharth** 2018-03-22 09:36 UTC
