### ISSUE TITLE
Installer fails - Step 4.2

### ISSUE THREAD

**Issue by pmona** [shivasiddharth/GassistPi#184] opened 2018-02-04 22:42 UTC
When I attempt to run the installer in section CONTINUE after SETTING UP AUDIO, step 4.2:
sudo /home/pi/GassistPi/scripts/gassist-installer-pi3.sh

It errors out with the following:

Collecting pycryptodomex>=3.0 (from gpsoauth>=0.2.0->gmusicapi>=11.0.0->-r /home/pi/GassistPi/Requirements/GassistPi-pip-requirements.txt (line 6))
Using cached pycryptodomex-3.4.11.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "/tmp/pip-build-zu3w3oyv/pycryptodomex/setup.py", line 107, in 
for line in open(os.path.join("lib", "Crypto", "init.py")):
FileNotFoundError: [Errno 2] No such file or directory: 'lib/Crypto/init.py'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zu3w3oyv/pycryptodomex/

I started this build from scratch with a fresh install of raspbian.

Can anyone provide any direction to resolve this?

**Comment by shivasiddharth** [comment] 2018-02-04 22:55
duplicate of #182

**Closed by shivasiddharth** 2018-02-04 22:55 UTC
Labels: duplicate
