### ISSUE TITLE
Errors after upgrade/update

### ISSUE THREAD

**Issue by IngmarG** [shivasiddharth/GassistPi#657] opened 2018-11-29 15:38 UTC
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
cat /proc/cpuinfo

_processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 57.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 57.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 57.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 57.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : a01041
Serial          : 00000000cb14a12b_

cat /etc/os-release

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Paste your Board and OS details here.   
```

### Describe the bug:
```

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

### If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### If answer to question 2 is No, then proceed further.
### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### If answer to question 4 is No, then proceed further.
### Manually start the assistant. For guidelines to start the assistant manually refer [this](https://github.com/shivasiddharth/GassistPi#manually-start-the-assistant)

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
ERROR:__main__:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 354, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 347, in main
    camera(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 95, in camera
    say("Taking frontal picture in 10 seconds")
  File "/home/pi/GassistPi/src/actions.py", line 76, in say
    words= translator.translate(words, dest=language)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 187, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 66, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by shivasiddharth** [comment] 2018-11-29 15:48
> ### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
> Yes/No

Duplicate of #534 . This is why sticking to issue template is important.

**Closed by shivasiddharth** 2018-11-29 15:48 UTC

**Comment by IngmarG** [comment] 2018-11-29 15:56
Do you mean the update/upgrade also changes the environment? Because I was one of the first contributors to that issue 534. I already made the changes AND already did an update/upgradeoir two.

**Comment by shivasiddharth** [comment] 2018-11-29 16:01
Sorry, i did not see that you had been a part of that discussion. Existing file was manually overwritten, so yes updates replace the overwritten files. If you are ok with testing a newer method of translation, that will not create this error, i shall reopen and relabel this issue. We can close #534 once and for all.

**Comment by IngmarG** [comment] 2018-11-29 16:05
What do you mean with " a newer method of translation" ?

Always open to test something new. 

On the issue:
I thought hat was exactly the point of an environment: to preserve it from changes.
I'll apply the patches and see what happens.

**Comment by shivasiddharth** [comment] 2018-11-29 16:12
"newer method" meaning a python package alternative to googletrans.

**Comment by shivasiddharth** [comment] 2018-11-29 16:16
I was of the thought that you ran the update within the environment.

**Comment by IngmarG** [comment] 2018-11-29 16:19
No, just in the main console. That's why I was surprised that I got this error again.

**Comment by shivasiddharth** [comment] 2018-11-29 16:30
Within the environment install goslate using:
```
source env/bin/activate
pip install goslate
```
Replace your existing actions.py file with the updated one from master. See if it works.

**Comment by IngmarG** [comment] 2018-11-29 16:52
My actions.py is a completely stripped down version of yours (because I just needed it to control a camera. no Kodi, no KS,l no Hue, no ...).
So i'll have to compare my lines to your new ones.
I'll work on it this evening and let you know (in this thread).

**Comment by IngmarG** [comment] 2018-11-30 01:01
Didn't work for me.
What did work was updating to the latest gTTS-Token (v1.1.3) (https://pypi.org/project/gTTS-token/) and a forked GoogleTrans which takes that gTTS-Token into account (https://github.com/BoseCorp/py-googletrans)


Sadly enough, I'm running into another issue now:
ERROR:__main__:'charmap' codec can't encode character '\u2019' in position 33: character maps to <undefined>
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 354, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 337, in main
    self.process_event(event)
  File "/home/pi/GassistPi/src/main.py", line 170, in process_event
    print(event)
  File "/usr/lib/python3.5/encodings/iso8859_15.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 33: character maps to <undefined>

**Comment by shivasiddharth** [comment] 2018-11-30 11:30
usually, unicode errors are related to google's cloud. Try giving it sometime.
