### ISSUE TITLE
Hotword not working on RasPi 0W, everything else does

### ISSUE THREAD

**Issue by jbrepogmailcom** [shivasiddharth/GassistPi#935] opened 2019-07-19 18:46 UTC
**IMPORTANT NOTICE  
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.**  

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**    

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
```
```
Paste your Board and OS details here.   
```
pi@raspberrypi:~ $ cat /proc/cpuinfo  
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 00000000335907fa
pi@raspberrypi:~ $ cat /etc/os-release  
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
### Describe the bug:
```
Hotword detection started by pushbutton.py, is waiting after GPIO init, Sound plays and Assistant says HI. Then it does not react to hotword. When assistant started during install, it worked properly upon pressing ENTER

pi@raspberrypi:~/GassistPi/src $ sudo systemctl stop gassistpi.service
pi@raspberrypi:~/GassistPi/src $ /home/${USER}/env/bin/python -u /home/${USER}/GassistPi/src/pushbutton.py --project-id r2d2-190720  --device-model-id r2d2-190720-raspi0w-7glm3f
/home/pi/env/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/pi/.local/share/gmusicapi/mobileclient.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
2019-07-19 19:39:28,927 - gmusicapi.Mobileclient1 (shared:183) [WARNING]: could not retrieve oauth credentials from ''/home/pi/.local/share/gmusicapi/mobileclient.cred''
[013db8f8] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[01430d88] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
USB-DAC
Initializing GPIOs 5 and 6 for assistant activity indication


```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

### If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

### Attach the log file named Gassistpi.log
Log file can be found in /tmp/ directory

**Comment by shivasiddharth** [comment] 2019-07-19 19:05
Duplicate of #820 Follow the issue there.

**Closed by shivasiddharth** 2019-07-19 19:05 UTC

**Comment by jbrepogmailcom** [comment] 2019-07-19 19:11
Hello, sorry I am confused. The feature list:

"24. Custom wakeword activation for all Pi boards."

while you write:
"I have already mentioned this a number of times. Pi Zero does not have Ok_Google wakewording."

What does it mean for Raspberry Zero? That it works with custom wakeword BUT NOT with OK_Google?
