### ISSUE TITLE
Failed to register device

### ISSUE THREAD

**Issue by steckhan** [shivasiddharth/GassistPi#1140] opened 2021-11-04 18:22 UTC
### Which branch of GassistPi are you using ?
Recent Master

### Board and OS details:    
Open a terminal and run   
```
cat /proc/cpuinfo  
cat /etc/os-release  
cat /etc/rpi-issue
```
```
pi@raspberrypi:~ $ cat /proc/cpuinfo  
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 000000000aed72c1
Model           : Raspberry Pi 3 Model B Rev 1.2
pi@raspberrypi:~ $ cat /etc/os-release  
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ cat /etc/rpi-issue
Raspberry Pi reference 2021-05-07
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, dcfd74d7d1fa293065ac6d565711e9ff891fe2b8, stage5
```

### Describe the bug:
```

Google.assistant.library.device_helpers.RegistrationError: Failed to register device INVALID_ARGUMENT (400): Request contains an invalid argument.

```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues)?
The Google‘s own googlesamples-assistant-pushtotalk Is working correctly ,
So my installation seems fine

### 2. Is the issue related to assistant installation ?
Yes/No ?

### If answer to question 2 is Yes, then attach the contents of terminal as a file or paste it below.
```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes if I enable the service, it tries to restart without success 

### If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

home/${USER}/env/bin/python -u /home/${USER}/GassistPi/src/main.py --project_id 'project-332362718115' --device_model_id 'talkingpi2-307c6-talkingpi2-94o7ms'

```

### Paste the contents of the terminal below
```

/home/pi/env/lib/python3.7/site-packages/google/assistant/library/assistant.py:90: DeprecationWarning: Google Assistant Library for Python is deprecated
  warnings.warn('Google Assistant Library for Python is deprecated', DeprecationWarning)
device_model_id: talkingpi2-307c6-talkingpi2-94o7ms
device_id: CED3ED30330F4F4F1C2F23280DF01D28

2021-11-04 19:21:29,213 : ERROR : Failed to register device INVALID_ARGUMENT (400): Request contains an invalid argument.
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 1131, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 1109, in main
    device_model_id, device_id, args.nickname)
  File "/home/pi/env/lib/python3.7/site-packages/google/assistant/library/device_helpers.py", line 88, in register_device
    raise RegistrationError(r, device_model_id)
google.assistant.library.device_helpers.RegistrationError: Failed to register device INVALID_ARGUMENT (400): Request contains an invalid argument.

```

**Comment by shivasiddharth** [comment] 2021-11-07 17:33
Duplicate of #1070

**Closed by shivasiddharth** 2021-11-07 17:33 UTC
