### ISSUE TITLE
Youtube Playback

### ISSUE THREAD

**Issue by valascus** [shivasiddharth/GassistPi#55] opened 2017-11-06 20:50 UTC
Raspberry Says: Playing $music but nothing is played.

**Comment by shivasiddharth** [comment] 2017-11-06 21:04
open a terminal and enter he following
`mpsyt set player chromium-browser, set playerargs ,exit`

close the terminal and try again

**Comment by valascus** [comment] 2017-11-07 00:14
Nope.
I tried to play some music directly at mpsyt. 
Says only: error. retrying

**Comment by valascus** [comment] 2017-11-07 02:32
Solved it. Didn't have mpv installed. Now, google assistant can't stop it.
Even pkill chromium can't stop it.

// Find out vlc is the one gassistpi uses, but can't get anything out of it. Chromium-browser was also not installed, but, even after installing it, it was not working. Only solved by installing mpv and setting it as player

**Comment by shivasiddharth** [comment] 2017-11-07 09:03
Normally when you update and upgrade the system, chromium will be installed, but to play it safe, i shall include it in the installer script now.  mpv has to be built and installed. That is why i have gone with with chromium instead. Since the issue is resolved, i am closing this.

**Closed by shivasiddharth** 2017-11-07 09:03 UTC

**Comment by valascus** [comment] 2017-11-07 16:01
probably it would't install, because i'm using the lite version of raspbian.
Thanks!
