### ISSUE TITLE
Google authorization code URL return with 500 response

### ISSUE THREAD

**Issue by Vino-git** [shivasiddharth/GassistPi#495] opened 2018-08-22 13:24 UTC
### Describe the bug:
```
HI, Once the successful installation. There is URL for getting google authorization code but it throws with 500 response. 

Kindly assist.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes/No

### 2. Is the issue related to assistant installation ?
Yes/No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes/No

### 4. Is the assistant service restarting automatically?
Yes/No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by shivasiddharth** [comment] 2018-08-22 13:29
The purpose issue template is being defeated. You should follow the template. 

> Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).

This has already been discussed in #476  Duplicate of #476

**Closed by shivasiddharth** 2018-08-22 13:29 UTC

**Comment by Vino-git** [comment] 2018-08-22 13:31
Oh sorry.
