### ISSUE TITLE
Change custom converstation langue

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#516] opened 2018-09-06 02:06 UTC
Hi, Its so perfect that you add the custom answer on the Gassist Pi but its would be great if the answer langue sync with google assistant sdk.so can you do a couple of change,please.

Thanks for reading this

**Comment by shivasiddharth** [comment] 2018-09-06 10:07
Duplicate of #510

**Closed by shivasiddharth** 2018-09-06 10:07 UTC
