### ISSUE TITLE
can not read custom commands

### ISSUE THREAD

**Issue by ykr412** [shivasiddharth/GassistPi#736] opened 2019-01-13 22:26 UTC
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "who are you"}

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
    stream.write(msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\uff1f' in position 119: ordinal not in range(256)
Call stack:
  File "/home/pi/GassistPi/src/main.py", line 844, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 836, in main
    self.custom_command(usrcmd)
  File "/home/pi/GassistPi/src/main.py", line 526, in custom_command
    say(selectedans[0])
  File "/home/pi/GassistPi/src/actions.py", line 318, in say
    gttssay(sayword,translanguage)
  File "/home/pi/GassistPi/src/actions.py", line 256, in gttssay
    tts = gTTS(text=phrase, lang=saylang)
  File "/home/pi/env/lib/python3.5/site-packages/gtts/tts.py", line 108, in __init__
    log.debug("%s: %s", k, v)
Message: '%s: %s'
Arguments: ('tokenizer_func', <bound method Tokenizer.run of re.compile('(?<=\\?).|(?<=\\!).|(?<=\\\uff1f).|(?<=\\\uff01).|(?<!\\.[a-z])\\. |(?<!\\.[a-z])\\, |\\\u2014|\\\u060c|\\\uff1a|\\)|\\[|\\:|\\¡|\\\uff0c|\\;|\\]|\\\u3002|\\\u2025|\\\n|\\\u2026|\\\u3001|\\(|\\¿', re.IGNORECASE) from: [<function tone_marks at 0x70c45348>, <function period_comma at 0x70c45390>, <function other_punctuation at 0x70c453d8>]>)
Segmentation fault

**Comment by aandroide** [comment] 2019-01-13 22:35
did you update the project? in case you did not do it, I suggest you update it because in the last 10 hours several changes have been made. read also the readme file for the new text to speech function

**Comment by ykr412** [comment] 2019-01-13 22:47
yes i have updated the project just now even i have implemented a new sd card from fresh

**Comment by aandroide** [comment] 2019-01-13 22:56
have you configured your config.yaml file well?

**Comment by ykr412** [comment] 2019-01-13 22:57
I did not touch the config.yaml i just used the custom conversation as set “who are you” and it crashed

**Comment by aandroide** [comment] 2019-01-13 23:10
you must configure the config.yaml file by entering your language preferences

**Comment by ykr412** [comment] 2019-01-13 23:13
Its set to default english ‘en-us’

**Comment by aandroide** [comment] 2019-01-13 23:19
open the tmp folder and publish your gassistpi.log file here

**Comment by aandroide** [comment] 2019-01-13 23:38
the temp folder is outside gassistpi

**Comment by ykr412** [comment] 2019-01-13 23:40
There is nothing inside the templates folder

**Comment by aandroide** [comment] 2019-01-13 23:45
![annotazione 2019-01-14 004511](https://user-images.githubusercontent.com/14141574/51092277-b83bbf00-1795-11e9-880a-74deeac432ac.jpg)

**Comment by ykr412** [comment] 2019-01-13 23:48
2019-01-14 02:18:57,954 : DEBUG : Making request: POST https://accounts.google.com/o/oauth2/token
2019-01-14 02:18:57,969 : DEBUG : Starting new HTTPS connection (1): accounts.google.com:443
2019-01-14 02:18:58,618 : DEBUG : https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2019-01-14 02:19:08,464 : DEBUG : slow: False
2019-01-14 02:19:08,466 : DEBUG : lang_check: True
2019-01-14 02:19:08,466 : DEBUG : text: I am not the one you expect to be
2019-01-14 02:19:08,508 : DEBUG : lang: en
2019-01-14 02:19:08,509 : DEBUG : pre_processor_funcs: [<function tone_marks at 0x70cd5df8>, <function end_of_line at 0x70cd4228>, <function abbreviations at 0x70cd4270>, <function word_sub at 0x70cd42b8>]
2019-01-14 02:19:08,556 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:19:08,812 : DEBUG : http://translate.google.com:80 "GET / HTTP/1.1" 302 226
2019-01-14 02:19:08,856 : DEBUG : Starting new HTTPS connection (1): translate.google.com:443
2019-01-14 02:19:09,502 : DEBUG : https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2019-01-14 02:19:09,849 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:19:09,995 : DEBUG : http://translate.google.com:80 "GET //translate/releases/twsfe_w_20190107_RC00/r/js/translate_m.js HTTP/1.1" 200 255
2019-01-14 02:19:10,017 : DEBUG : langs: {'en-nz': 'English (New Zealand)', 'en-tz': 'English (Tanzania)', 'en-ie': 'English (Ireland)', 'en-gh': 'English (Ghana)', 'en-ng': 'English (Nigeria)', 'pt-br': 'Portuguese (Brazil)', 'en-ca': 'English (Canada)', 'fr-fr': 'French (France)', 'en-in': 'English (India)', 'fr-ca': 'French (Canada)', 'zh-tw': 'Chinese (Mandarin/Taiwan)', 'en-us': 'English (US)', 'en-au': 'English (Australia)', 'es-es': 'Spanish (Spain)', 'en-ph': 'English (Philippines)', 'es-us': 'Spanish (United States)', 'en-uk': 'English (UK)', 'en-za': 'English (South Africa)', 'pt-pt': 'Portuguese (Portugal)', 'zh-cn': 'Chinese (Mandarin/China)', 'en-gb': 'English (UK)'}
2019-01-14 02:24:21,395 : DEBUG : Making request: POST https://accounts.google.com/o/oauth2/token
2019-01-14 02:24:21,410 : DEBUG : Starting new HTTPS connection (1): accounts.google.com:443
2019-01-14 02:24:22,112 : DEBUG : https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2019-01-14 02:24:30,961 : DEBUG : lang_check: True
2019-01-14 02:24:32,797 : DEBUG : lang: en
2019-01-14 02:24:32,798 : DEBUG : text: I am not the one you expect to be
2019-01-14 02:24:32,799 : DEBUG : pre_processor_funcs: [<function tone_marks at 0x70cc7df8>, <function end_of_line at 0x70cc8228>, <function abbreviations at 0x70cc8270>, <function word_sub at 0x70cc82b8>]
2019-01-14 02:24:32,819 : DEBUG : slow: False
2019-01-14 02:24:32,849 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:24:33,121 : DEBUG : http://translate.google.com:80 "GET / HTTP/1.1" 302 226
2019-01-14 02:24:33,161 : DEBUG : Starting new HTTPS connection (1): translate.google.com:443
2019-01-14 02:24:33,809 : DEBUG : https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2019-01-14 02:24:34,163 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:24:34,303 : DEBUG : http://translate.google.com:80 "GET //translate/releases/twsfe_w_20190107_RC00/r/js/translate_m.js HTTP/1.1" 200 255
2019-01-14 02:24:34,324 : DEBUG : langs: {'en-ng': 'English (Nigeria)', 'en-in': 'English (India)', 'en-uk': 'English (UK)', 'pt-pt': 'Portuguese (Portugal)', 'fr-ca': 'French (Canada)', 'en-ie': 'English (Ireland)', 'en-za': 'English (South Africa)', 'es-es': 'Spanish (Spain)', 'en-ph': 'English (Philippines)', 'en-gb': 'English (UK)', 'fr-fr': 'French (France)', 'en-gh': 'English (Ghana)', 'pt-br': 'Portuguese (Brazil)', 'zh-cn': 'Chinese (Mandarin/China)', 'es-us': 'Spanish (United States)', 'en-nz': 'English (New Zealand)', 'en-ca': 'English (Canada)', 'en-us': 'English (US)', 'en-au': 'English (Australia)', 'en-tz': 'English (Tanzania)', 'zh-tw': 'Chinese (Mandarin/Taiwan)'}
2019-01-14 02:28:10,999 : DEBUG : Making request: POST https://accounts.google.com/o/oauth2/token
2019-01-14 02:28:11,015 : DEBUG : Starting new HTTPS connection (1): accounts.google.com:443
2019-01-14 02:30:32,818 : DEBUG : Making request: POST https://accounts.google.com/o/oauth2/token
2019-01-14 02:30:32,833 : DEBUG : Starting new HTTPS connection (1): accounts.google.com:443
2019-01-14 02:30:33,549 : DEBUG : https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2019-01-14 02:30:42,858 : DEBUG : pre_processor_funcs: [<function tone_marks at 0x70c9ddf8>, <function end_of_line at 0x70c9e228>, <function abbreviations at 0x70c9e270>, <function word_sub at 0x70c9e2b8>]
2019-01-14 02:30:42,860 : DEBUG : lang: en
2019-01-14 02:30:42,861 : DEBUG : lang_check: True
2019-01-14 02:30:42,862 : DEBUG : text: Who do you think I am
2019-01-14 02:30:42,863 : DEBUG : slow: False
2019-01-14 02:30:42,894 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:30:43,143 : DEBUG : http://translate.google.com:80 "GET / HTTP/1.1" 302 226
2019-01-14 02:30:43,171 : DEBUG : Starting new HTTPS connection (1): translate.google.com:443
2019-01-14 02:30:43,768 : DEBUG : https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2019-01-14 02:30:44,094 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:30:45,288 : DEBUG : http://translate.google.com:80 "GET //translate/releases/twsfe_w_20190107_RC00/r/js/translate_m.js HTTP/1.1" 200 255
2019-01-14 02:30:45,314 : DEBUG : langs: {'en-us': 'English (US)', 'en-ca': 'English (Canada)', 'zh-tw': 'Chinese (Mandarin/Taiwan)', 'en-ph': 'English (Philippines)', 'en-ng': 'English (Nigeria)', 'en-in': 'English (India)', 'en-tz': 'English (Tanzania)', 'fr-fr': 'French (France)', 'es-es': 'Spanish (Spain)', 'pt-pt': 'Portuguese (Portugal)', 'fr-ca': 'French (Canada)', 'es-us': 'Spanish (United States)', 'en-uk': 'English (UK)', 'en-ie': 'English (Ireland)', 'zh-cn': 'Chinese (Mandarin/China)', 'pt-br': 'Portuguese (Brazil)', 'en-au': 'English (Australia)', 'en-gh': 'English (Ghana)', 'en-za': 'English (South Africa)', 'en-nz': 'English (New Zealand)', 'en-gb': 'English (UK)'}
2019-01-14 02:34:56,292 : DEBUG : Making request: POST https://accounts.google.com/o/oauth2/token
2019-01-14 02:34:56,307 : DEBUG : Starting new HTTPS connection (1): accounts.google.com:443
2019-01-14 02:34:56,855 : DEBUG : https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2019-01-14 02:35:20,573 : DEBUG : lang_check: True
2019-01-14 02:35:20,574 : DEBUG : slow: False
2019-01-14 02:35:20,575 : DEBUG : pre_processor_funcs: [<function tone_marks at 0x70c79df8>, <function end_of_line at 0x70c7a228>, <function abbreviations at 0x70c7a270>, <function word_sub at 0x70c7a2b8>]
2019-01-14 02:35:20,576 : DEBUG : text: What bothers you
2019-01-14 02:35:20,601 : DEBUG : lang: en
2019-01-14 02:35:20,638 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:35:20,879 : DEBUG : http://translate.google.com:80 "GET / HTTP/1.1" 302 226
2019-01-14 02:35:20,912 : DEBUG : Starting new HTTPS connection (1): translate.google.com:443
2019-01-14 02:35:21,477 : DEBUG : https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2019-01-14 02:35:21,808 : DEBUG : Starting new HTTP connection (1): translate.google.com:80
2019-01-14 02:35:21,946 : DEBUG : http://translate.google.com:80 "GET //translate/releases/twsfe_w_20190107_RC00/r/js/translate_m.js HTTP/1.1" 200 255
2019-01-14 02:35:21,971 : DEBUG : langs: {'zh-cn': 'Chinese (Mandarin/China)', 'en-in': 'English (India)', 'en-gb': 'English (UK)', 'es-es': 'Spanish (Spain)', 'en-gh': 'English (Ghana)', 'en-ie': 'English (Ireland)', 'en-us': 'English (US)', 'en-za': 'English (South Africa)', 'en-nz': 'English (New Zealand)', 'en-ng': 'English (Nigeria)', 'pt-br': 'Portuguese (Brazil)', 'es-us': 'Spanish (United States)', 'fr-fr': 'French (France)', 'fr-ca': 'French (Canada)', 'en-ph': 'English (Philippines)', 'en-ca': 'English (Canada)', 'zh-tw': 'Chinese (Mandarin/Taiwan)', 'en-au': 'English (Australia)', 'en-uk': 'English (UK)', 'en-tz': 'English (Tanzania)', 'pt-pt': 'Portuguese (Portugal)'}

**Comment by shivasiddharth** [comment] 2019-01-14 00:14
@ykr412 , In the config.yaml what are the answers that you have for custom questions ? do you have something with a ' apostrophe ?

**Comment by ykr412** [comment] 2019-01-14 00:46
No just the quistions you have entered

**Comment by shivasiddharth** [comment] 2019-01-14 10:40
@ykr412  Can you attach the file here. Do not copy paste.

**Comment by shivasiddharth** [comment] 2019-01-16 12:11
This issue is a duplicate of #448. If you had used the issue template, you would have been re-directed there. Or even a simple google search of this issue would have taken you there. 
![image](https://user-images.githubusercontent.com/18142081/51248370-cc471280-1987-11e9-92a9-367e4134c2d8.png)

**Closed by shivasiddharth** 2019-01-16 12:11 UTC
