### ISSUE TITLE
custom wakeword not working 

### ISSUE THREAD

**Issue by mra1984** [shivasiddharth/GassistPi#526] opened 2018-09-14 15:04 UTC
### Describe the bug:
```
Have followed custom wakeword activation instructions but Alexa does not work, nor does my custom *.pmdl snowboy file.  Any ideas please?  I tried searching old issues but everything is enabled and files are loaded in the right location. 
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
Yes

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```

```

### Paste the contents of the terminal below
```

```

**Comment by Pealy** [comment] 2018-09-15 11:34
I thought I had the same problem until I tried speaking right next to my USB mic and Alexa was recognised.
I had set ok_google to Disabled and commented out the snowboy.umdl line

**Comment by shivasiddharth** [comment] 2018-09-15 12:29
Duplicate of #505

**Closed by shivasiddharth** 2018-09-15 12:29 UTC
