### ISSUE TITLE
service-installer.sh not running

### ISSUE THREAD

**Issue by pallaprasannakumar02** [shivasiddharth/GassistPi#93] opened 2017-12-19 19:53 UTC
service-installer.sh is not running

Followed entire process but nothing is running on startup

**Comment by shivasiddharth** [comment] 2017-12-19 19:57
After executing the service installer, you should enable the services. What do you mean like nothing is running on startup ? You dont even hear the "welcome audio"?

**Comment by pallaprasannakumar02** [comment] 2017-12-20 03:25
yeah,  i have did the same thing and rebooted, i didnt heard welcome audio

**Comment by shivasiddharth** [comment] 2017-12-20 10:33
Did you see this. #86 ?

**Comment by shivasiddharth** [comment] 2017-12-30 12:53
Since, nothing was communicated after, the issue is deemed resolved. Closing this !

**Closed by shivasiddharth** 2017-12-30 12:53 UTC
