### ISSUE TITLE
No matching playlist when applying Deezer command with correct Syntax

### ISSUE THREAD

**Issue by rutherb** [shivasiddharth/GassistPi#624] opened 2018-11-08 11:55 UTC
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist number one from Deezer"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play playlist number one from Deezer"}
stopping vlc
/home/pi/env/lib/python3.5/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
No matching playlists found
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

Directory: /tmp/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: say.mp3 ...

MPEG 2.0 L III cbr32 24000 mono

[0:02] Decoding of say.mp3 finished.
ERROR:__main__:local variable 'tracklisturl' referenced before assignment
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 672, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 664, in main
    deezer_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1507, in deezer_playlist_select
    deezer_tracks_response = requests.get(tracklisturl,verify=False)
UnboundLocalError: local variable 'tracklisturl' referenced before assignment

_Originally posted by @rutherb in https://github.com/shivasiddharth/GassistPi/issues/618#issuecomment-436968676_

**Comment by shivasiddharth** [comment] 2018-11-08 12:00
Please do not post duplicate issues. If the closed issue was not resolved, please reopen that. Duplicate of #618

**Closed by shivasiddharth** 2018-11-08 12:00 UTC
