### ISSUE TITLE
Spotify Crashes Assistant

### ISSUE THREAD

**Issue by TheEndernaut** [shivasiddharth/GassistPi#577] opened 2018-10-15 02:39 UTC
### Describe the bug:
```
Whevever I try to play something from spotify, y assistant crashes. I have already inputted my client_secret and client_id into the config.yaml.
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```

```

### Paste the command below, that crashed the assistant
```
Play Music on Spotify
(Music is the name of my playlist)
```

### Paste the contents of the terminal below
```
  {"text": "play music on Spotify"}
stopping vlc
ERROR:__main__:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 666, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 650, in main
    spotify_playlist_select(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1343, in spotify_playlist_select
    say("Getting music links")
  File "/home/pi/GassistPi/src/actions.py", line 216, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 207, in trans
    transword= translator.translate(words, dest=lang)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 180, in do
    self._update()
  File "/home/pi/env/lib/python3.5/site-packages/googletrans/gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'


```

### Attach the log file. Log file can be found in /tmp directory. Remember to copy your log file before shutting down or restarting the Pi.
There was nothing in the /tmp directory, didn't restart my pi.

**Comment by shivasiddharth** [comment] 2018-10-15 09:05
> Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

Duplicate of #534

**Closed by shivasiddharth** 2018-10-15 09:05 UTC
