### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Triscuit47** [shivasiddharth/GassistPi#358] opened 2018-05-26 07:20 UTC
### Describe the bug:
After executing the script gassist-installer-pi3.sh it fails at the last step with "segmentation fault" error.

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
Yes

## If answer to question 2 is Yes, then paste the contents of the terminal below.
`Testing the installed google assistant. Make a note of the generated Device-Id`
`device_model_id: <model>`
`device_id: <id>`

`/home/pi/GassistPi/scripts/gassist-installer-pi3.sh: line 65:  2244 Segmentation fault      googlesamples-assistant-hotword --project_id $projid --device_model_id $modelid`

Also, if I try starting the Assistant it does start normally but when I use the hotword the Assistant replies with something among "there has been a problem try again in a few seconds".

**Comment by shivasiddharth** [comment] 2018-05-26 09:47
You tend to get the segmentation error, if the model_id and project_id is mentioned incorrectly. The something went wrong is due a network glitch (can be a slow network or no network), That has already been discussed in a number of issues already.

**Comment by kissrobber** [comment] 2018-05-27 15:45
I'm in the same situation too.

>  That has already been discussed in a number of issues already.

Which issues?
https://github.com/shivasiddharth/GassistPi/issues?utf8=%E2%9C%93&q=Segmentation+Fault

**Comment by Triscuit47** [comment] 2018-05-27 15:48
Before the 0.5.0 update it worked perfectly, after I did the fresh install it started doing it, I will double check the model id and project id. Thank you.

**Comment by shivasiddharth** [comment] 2018-05-27 16:20
@kissrobber , The network glitch thingy has been already talked about in a number of issues. I never said that segmentation issue was discussed.

**Comment by Triscuit47** [comment] 2018-05-27 21:46
Ok, I've tried it again. Same steps, fresh OS -> install bang, segmentation fault. I paid extra attention to the project and model IDs. I don't know what else to do.

**Comment by shivasiddharth** [comment] 2018-05-27 22:38
Can you manually run the assistant and paste the contents of the terminal.? You can find the syntax to manually run the assistant in the readme.

**Comment by Triscuit47** [comment] 2018-05-27 22:44
This device is not registered. This means you will not be able to use
    Device Actions or see your device in Assistant Settings. In order to
    register this device follow instructions at:

    https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device

ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED

**Comment by shivasiddharth** [comment] 2018-05-27 23:05
When you were prompted for the credentials name, did you enter it along with the path? it should be like for example /home/pi/credentials.json if you placed the credentials file in the /home/pi/ directory.

If not then, you need not re run the installer, just enter the following in the terminal sequentially.

`source env/bin/activate`
```
google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
          --scope https://www.googleapis.com/auth/gcm \
          --save --headless --client-secrets /home/pi/credentials.json
```
Now things should work normally.

**Comment by shivasiddharth** [comment] 2018-05-27 23:33
1. Have you placed the credentials file in the /home/pi/ directory? 
2. The credentials file should be from the aactions console and not the google cloud project console?
3. What is the name of the credentials file that you have downloaded?

**Comment by Triscuit47** [comment] 2018-05-27 23:36
1. Yes
2. It's from https://console.actions.google.com/u/0/project/<project-name>/deviceregistration/ exactly
3. credentials.json - didn't rename it

**Comment by shivasiddharth** [comment] 2018-05-28 06:07
If that is the case then, the steps that I mentioned should work for sure.

just enter the following in the terminal sequentially.

source env/bin/activate

google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
          --scope https://www.googleapis.com/auth/gcm \
          --save --headless --client-secrets /home/pi/credentials.json

**Comment by shivasiddharth** [comment] 2018-05-28 06:12
If that is the case, then you should be able to register using the steps that i previously mentioned.

Just enter the following in the terminal sequentially.

`source env/bin/activate`

```
google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
          --scope https://www.googleapis.com/auth/gcm \
          --save --headless --client-secrets /home/pi/credentials.json
```
This should generate the authorization link and help you register.

**Comment by Triscuit47** [comment] 2018-05-28 08:30
Yeah I did that and it still didn't work, here was the result of it

`pi@raspberrypi:~ $ source env/bin/activate`
`(env)pi@raspberrypi:~ $ google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \`
`> --scope https://www.googleapis.com/auth/gcm \`
`> --save --headless --client-secrets /home/pi/credentials.json`
`Please visit this URL to authorize this application:long-ass-link`
`Enter the authorization code: long-ass-code`
`credentials saved: /home/pi/.config/google-oauthlib-tool/credentials.json`

**Comment by Triscuit47** [comment] 2018-05-28 09:30
I did try to start it manually after I've authorized it with the code you suggested but it still shows the device is not registered, I feel like it's a dumb mistake on my part I will do another fresh install with a new project and will pay extra care of the steps, third time's the charm right? I will comment after the result.

**Comment by Triscuit47** [comment] 2018-05-28 09:48
Nope, nothing. Same 'device is not registered' error.

**Comment by shivasiddharth** [comment] 2018-05-28 11:28
Can you paste the command that you used to manually start the assistant?

**Comment by n0tz0b** [comment] 2018-05-28 11:43
I'm also getting the segmentation fault error at the end of gassist-installer-pi3.sh script and received the not registered message. I followed the link and can now see a device on googles deviceregistration page.

I have also tried following the installing the Google Assistant Library as per [https://developers.google.com/assistant/sdk/guides/library/python/embed/setup](https://developers.google.com/assistant/sdk/guides/library/python/embed/setup) with similar results. 

Could we have setup our developer accounts / device registration incorrectly?

I noticed the installer script was updated 12hrs ago. What was changed?

Going to try a fresh download and install, will specify the full path to credentials.json this time in the hope thats the issue.

**Comment by Triscuit47** [comment] 2018-05-28 11:51
@shivasiddharth 
`/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'my-model-id'`

**Comment by shivasiddharth** [comment] 2018-05-28 12:01
Hope you replaced 'my-model-id' in that with your model id ?

**Comment by shivasiddharth** [comment] 2018-05-28 12:56
I can think of only one issue, the device registration might not have been setup properly online.  Google's instructions are all over the place. I shall update the readme with a proper instruction. See if you can get things working following that.

**Comment by Triscuit47** [comment] 2018-05-28 13:00
Now that's the funny thing. I did the same steps I did before the 0.5.0 update and worked like a charm without any problems. I will wait for your update. Thank you.

**Comment by n0tz0b** [comment] 2018-05-28 13:09
Fresh install and full path made no difference still getting 

>  This device is not registered. This means you will not be able to use
>     Device Actions or see your device in Assistant Settings. In order to
>     register this device follow instructions at:
> 
>     https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device
> 

if i use:-
/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'my-model-id'

Also get same message if i set my-model-id as    randomcrap   have tried inside & without quotes

I have followed link in instuction above and created new device. Same conclusion.

If I use 

> source env/bin/activate
> 
> googlesamples-assistant-hotword --project_id 'My-Project-ID' --device_model_id 'My-ProjectID-MyProduct-6xchar'

I get Segmentation fault error. If I use random data as project-id & model-id i get same Segmentation fault error

**Comment by shivasiddharth** [comment] 2018-05-28 13:18
@n0tz0b , Have you enabled the Assistant API in the Cloud Console ? And setting the ids to to some random values does not help.

**Comment by n0tz0b** [comment] 2018-05-28 14:30
@shivasiddharth , Yes API assistant is enabled. Figured the random data would prove that the command is ignoring the model-id.

Anyhow....... Its working :)

I followed the link [https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device) to create new device, added ALL traits(not sure if this was needed). Downloaded credentials.json and copied it to /home/pi. Ran `/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'my-NEW-model-id'` and didn't get the error message
> This device is not registered. This means you will not be able to use
> Device Actions or see your device in Assistant Settings. In order to
> register this device follow instructions at:

However I also didn't get the message

> Registering...Done.

Is that OK?

I made the mistake of renaming the json so as I could have multiple versions in /home/pi. [https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device](https://developers.google.com/assistant/sdk/guides/library/python/embed/register-device) confirms NOT to do this.

As you mentioned above the new documentation is "all over the place". I can confirm the device_model_id looks like 'My-ProjectID-MyProduct-6xchar'

Great job..... keep up the good work.

**Comment by shivasiddharth** [comment] 2018-05-28 14:50
Issue Resolved. Closing the thread.

**Closed by shivasiddharth** 2018-05-28 14:50 UTC

**Comment by Triscuit47** [comment] 2018-05-28 16:07
Yep as I was saying, it was a dumb mistake on my part, I forgot to enable the Assistant API sorry for wasting your time. And Thanks for making the time to help me .

**Comment by madmadda** [comment] 2018-06-14 19:04
ohhh my god i think i have done the same thing, forgeting to enableing it, one momment to check
also sorry for posting to something closed

**Comment by akshaybengani** [comment] 2018-12-24 06:16
> Hope you replaced 'my-model-id' in that with your model id?

Actually, I am setting up assistant on my laptop only, therefore, how do I register as a device on the actions console since the actions console asks for device type and there is no option for PC or Computer or such, there are options like Camera, Washer, Speaker, Auto etc.

**Comment by sethlloydcollins** [comment] 2019-07-10 18:56
Hi

So I am having the same issue. When running **_/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'model id here'_** I keep getting **Segmentation Fault**. 

To be noted I have tried several projects and each of them report Segmentation Fault when running the **_googlesamples.assistant.hotword --device-model-id 'model-id-here'_** command. Other than that all is working. 

With my limited knowledge I would imagine there being something set up in my Google project incorrectly, but the device is certainly registered and the API is definitely enabled. Also worth noting is that this does indeed work if I use the googlesamples-assistant-pushtotalk --project-id <projectid> --device-model-id <deviceid> sample, but I have to press enter each time, which defeats the purpose of the whole project. 

I am running Raspbian Buster on 3b+.

Please please please assist, I am getting frustrated after trying for 2 weeks.
