### ISSUE TITLE
URLLIB problem

### ISSUE THREAD

**Issue by BarryAlvord** [shivasiddharth/GassistPi#673] opened 2018-12-03 12:22 UTC
here is my terminal output please help
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play Last Christmas from YouTube"}
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play Last Christmas from YouTube"}
stopping vlc
ERROR:__main__:HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/actions.py", line 1030, in YouTube_No_Autoplay
    say("Getting youtube link")
  File "/home/pi/GassistPi/src/actions.py", line 224, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 218, in trans
    transword= translator.translate(words, lang)
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 409, in translate
    return _unwrapper_single_element(self._translate_single_text(text, target_language, source_language))
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 334, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 203, in _execute
    yield each()
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 332, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 251, in _basic_translate
    response_content = self._open_url(url)
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 191, in _open_url
    raise e
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 181, in _open_url
    response = self._opener.open(request, timeout=self._TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 692, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 549, in main
    YouTube_No_Autoplay(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 1043, in YouTube_No_Autoplay
    say('It is no longer available in youtube')
  File "/home/pi/GassistPi/src/actions.py", line 224, in say
    newword=trans(words,language)
  File "/home/pi/GassistPi/src/actions.py", line 218, in trans
    transword= translator.translate(words, lang)
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 409, in translate
    return _unwrapper_single_element(self._translate_single_text(text, target_language, source_language))
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 334, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 203, in _execute
    yield each()
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 332, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 251, in _basic_translate
    response_content = self._open_url(url)
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 191, in _open_url
    raise e
  File "/home/pi/env/lib/python3.5/site-packages/goslate.py", line 181, in _open_url
    response = self._opener.open(request, timeout=self._TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

**Comment by shivasiddharth** [comment] 2018-12-03 12:58
Duplicate of #662.  Please go through the updated instructions in #534 . I repeat again, if the issue template is not used, the issue will be closed and will not be dealt with.

**Closed by shivasiddharth** 2018-12-03 12:58 UTC
