### ISSUE TITLE
SSL handshake timeout during gassist-installer-pi3.sh

### ISSUE THREAD

**Issue by ilioscio** [shivasiddharth/GassistPi#310] opened 2018-04-13 05:16 UTC
when running 'sudo /home/pi/GassistPi/scripts/gassist-installer-pi3.sh' I get the following error:

> Exception:
> Traceback (most recent call last):
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 350, in _make_request
>     self._validate_conn(conn)
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 837, in _validate_conn
>     conn.connect()
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 323, in connect
>     ssl_context=context)
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
>     _context=self)
>   File "/usr/lib/python3.5/ssl.py", line 760, in __init__
>     self.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
>     self._sslobj.do_handshake()
>   File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
>     self._sslobj.do_handshake()
> socket.timeout: _ssl.c:704: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
>     chunked=chunked)
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 353, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 313, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.piwheels.org', port=443): Read timed out. (read timeout=15)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/pi/env/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/commands/install.py", line 353, in run
>     wb.build(autobuilding=True)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
>     self.requirement_set.prepare_files(self.finder)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/home/pi/env/lib/python3.5/site-packages/pip/req/req_set.py", line 487, in _prepare_file
>     req_to_install, finder)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/req/req_set.py", line 428, in _check_skip_installed
>     req_to_install, upgrade_allowed)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/index.py", line 465, in find_requirement
>     all_candidates = self.find_all_candidates(req.name)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/index.py", line 423, in find_all_candidates
>     for page in self._get_pages(url_locations, project_name):
>   File "/home/pi/env/lib/python3.5/site-packages/pip/index.py", line 568, in _get_pages
>     page = self._get_page(location)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/index.py", line 683, in _get_page
>     return HTMLPage.get_page(link, session=self.session)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/index.py", line 792, in get_page
>     "Cache-Control": "max-age=600",
>   File "/home/pi/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/pi/env/lib/python3.5/site-packages/pip/download.py", line 386, in request
>     return super(PipSession, self).request(method, url, *args, **kwargs)
>   File "/home/pi/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/pi/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/pi/env/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
>     resp = super(CacheControlAdapter, self).send(request, **kw)
>   File "/home/pi/env/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
>     timeout=timeout
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/home/pi/env/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
>     total -= 1
> TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

My network connection seems fine otherwise and I am able to ping www.piwheels.org just fine. I have rebooted the device multiple times and the system is fully updated.

**Comment by shivasiddharth** [comment] 2018-04-25 08:38
Duplicate of #182

**Closed by shivasiddharth** 2018-04-25 08:38 UTC
