### ISSUE TITLE
getting error when applying deezer command

### ISSUE THREAD

**Issue by shaltut** [shivasiddharth/GassistPi#616] opened 2018-11-07 12:54 UTC
### Describe the bug:
```
when i give the command Play playlist number 1 from Deezer i got this error
```

### Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
Yes

### 2. Is the issue related to assistant installation ?
No

## If answer to question 2 is Yes, then paste the contents of the terminal below.

```

```

### 3. Does the assistant service start normally?
Yes

### 4. Is the assistant service restarting automatically?
No

## If answer to question 4 is Yes, then paste the contents of the terminal below.

```
![img_20181107_144541](https://user-images.githubusercontent.com/37026364/48132617-e3d59100-e29c-11e8-89e2-5b7c3684b454.jpg)

**Comment by shivasiddharth** [comment] 2018-11-07 12:57
> Did you go through or search the issues section to check if your issue was already discussed (either currently open issues or closed issues).
> Yes

Duplicate of #534

**Closed by shivasiddharth** 2018-11-07 12:57 UTC
