### ISSUE TITLE
Radio not playing

### ISSUE THREAD

**Issue by romeok01** [shivasiddharth/GassistPi#414] opened 2018-06-23 21:28 UTC
Hello, i edit config.yaml file and use   stationnames:
    - 'Radio 1'
    - 'Radio 2'
    - 'Radio 3'
    - 'Radio 5'
  stationlinks:
    - 'http://stream3.polskieradio.pl:8900/listen.pls'
When i say: "play Radio one" radio its not playing.
Please help me.

This is log file:
2018-06-23 23:26:26,602 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET /translate_a/single?tsel=0&tk=461897.96164&ie=UTF-8&hl=pl&ssel=0&otf=1&sl=auto&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&q=Tuning+into+Radio+1&client=t&tl=pl&oe=UTF-8 HTTP/1.1" 200 None
2018-06-23 23:26:26,609 DEBUG gtts.tts pre_processor_funcs: [<function tone_marks at 0x726834f8>, <function end_of_line at 0x726838e8>, <function abbreviations at 0x72683930>, <function word_sub at 0x72683978>]
2018-06-23 23:26:26,610 DEBUG gtts.tts lang: pl
2018-06-23 23:26:26,611 DEBUG gtts.tts slow: False
2018-06-23 23:26:26,611 DEBUG gtts.tts lang_check: True
2018-06-23 23:26:26,612 DEBUG gtts.tts tokenizer_func: <bound method Tokenizer.run of re.compile('(?<=\\?).|(?<=\\!).|(?<=\\？).|(?<=\\！).|(?<!\\.[a-z])\\. |(?<!\\.[a-z])\\, |\\)|\\。|\\;|\\：|\\]|\\…|\\‥|\\(|\\[|\\¿|\\—|\\，|\\、|\\¡|\\\n|\\:|\\،', re.IGNORECASE) from: [<function tone_marks at 0x72683a08>, <function period_comma at 0x72683a50>, <function other_punctuation at 0x72683a98>]>
2018-06-23 23:26:26,613 DEBUG gtts.tts text: Strojenie w Radio 1
2018-06-23 23:26:26,626 DEBUG urllib3.connectionpool Starting new HTTP connection (1): translate.google.com:80
2018-06-23 23:26:26,765 DEBUG urllib3.connectionpool http://translate.google.com:80 "GET / HTTP/1.1" 302 226
2018-06-23 23:26:26,788 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-06-23 23:26:27,136 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-06-23 23:26:27,343 DEBUG urllib3.connectionpool Starting new HTTP connection (1): translate.google.com:80
2018-06-23 23:26:27,478 DEBUG urllib3.connectionpool http://translate.google.com:80 "GET //translate/releases/twsfe_w_20180618_RC00/r/js/desktop_module_main.js HTTP/1.1" 200 165585
2018-06-23 23:26:27,855 DEBUG gtts.lang langs: {'km': 'Khmer', 'en-us': 'English (US)', 'en-ng': 'English (Nigeria)', 'hi': 'Hindi', 'en-ca': 'English (Canada)', 'tr': 'Turkish', 'pl': 'Polish', 'et': 'Estonian', 'cy': 'Welsh', 'en-za': 'English (South Africa)', 'es': 'Spanish', 'pt-pt': 'Portuguese (Portugal)', 'uk': 'Ukrainian', 'af': 'Afrikaans', 'fi': 'Finnish', 'ko': 'Korean', 'ru': 'Russian', 'hr': 'Croatian', 'lv': 'Latvian', 'ja': 'Japanese', 'ml': 'Malayalam', 'hu': 'Hungarian', 'en-uk': 'English (UK)', 'el': 'Greek', 'la': 'Latin', 'ne': 'Nepali', 'it': 'Italian', 'zh-tw': 'Chinese (Mandarin/Taiwan)', 'ro': 'Romanian', 'nl': 'Dutch', 'sw': 'Swahili', 'pt': 'Portuguese', 'sk': 'Slovak', 'pt-br': 'Portuguese (Brazil)', 'no': 'Norwegian', 'is': 'Icelandic', 'mk': 'Macedonian', 'sv': 'Swedish', 'bs': 'Bosnian', 'hy': 'Armenian', 'zh-cn': 'Chinese (Mandarin/China)', 'en-in': 'English (India)', 'id': 'Indonesian', 'fr-ca': 'French (Canada)', 'en-nz': 'English (New Zealand)', 'vi': 'Vietnamese', 'mr': 'Marathi', 'en-gb': 'English (UK)', 'en': 'English', 'en-au': 'English (Australia)', 'en-ph': 'English (Philippines)', 'fr': 'French', 'en-tz': 'English (Tanzania)', 'de': 'German', 'jw': 'Javanese', 'ta': 'Tamil', 'sr': 'Serbian', 'si': 'Sinhala', 'da': 'Danish', 'en-ie': 'English (Ireland)', 'bn': 'Bengali', 'en-gh': 'English (Ghana)', 'th': 'Thai', 'te': 'Telugu', 'sq': 'Albanian', 'eo': 'Esperanto', 'cs': 'Czech', 'es-es': 'Spanish (Spain)', 'su': 'Sundanese', 'ar': 'Arabic', 'fr-fr': 'French (France)', 'es-us': 'Spanish (United States)', 'tl': 'Filipino', 'ca': 'Catalan'}
2018-06-23 23:26:27,856 DEBUG gtts.tts pre-processing: <function tone_marks at 0x726834f8>
2018-06-23 23:26:27,857 DEBUG gtts.tts pre-processing: <function end_of_line at 0x726838e8>
2018-06-23 23:26:27,858 DEBUG gtts.tts pre-processing: <function abbreviations at 0x72683930>
2018-06-23 23:26:27,858 DEBUG gtts.tts pre-processing: <function word_sub at 0x72683978>
2018-06-23 23:26:27,859 DEBUG gtts.tts text_parts: 1
2018-06-23 23:26:27,865 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-06-23 23:26:28,177 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET / HTTP/1.1" 200 None
2018-06-23 23:26:28,193 DEBUG gtts.tts payload-0: {'idx': 0, 'ttsspeed': 1, 'textlen': 19, 'tk': '359566.198499', 'total': 1, 'ie': 'UTF-8', 'client': 'tw-ob', 'tl': 'pl', 'q': 'Strojenie w Radio 1'}
2018-06-23 23:26:28,200 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): translate.google.com:443
2018-06-23 23:26:28,527 DEBUG urllib3.connectionpool https://translate.google.com:443 "GET /translate_tts?idx=0&ttsspeed=1&textlen=19&tk=359566.198499&total=1&ie=UTF-8&client=tw-ob&tl=pl&q=Strojenie+w+Radio+1 HTTP/1.1" 200 7968
2018-06-23 23:26:28,538 DEBUG gtts.tts headers-0: {'Referer': 'http://translate.google.com/', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'keep-alive', 'Accept': '*/*'}
2018-06-23 23:26:28,539 DEBUG gtts.tts url-0: https://translate.google.com/translate_tts?idx=0&ttsspeed=1&textlen=19&tk=359566.198499&total=1&ie=UTF-8&client=tw-ob&tl=pl&q=Strojenie+w+Radio+1
2018-06-23 23:26:28,540 DEBUG gtts.tts status-0: 200
2018-06-23 23:26:28,542 DEBUG gtts.tts part-0 written to <_io.BufferedWriter name='/tmp/say.mp3'>
2018-06-23 23:26:28,543 DEBUG gtts.tts Saved to /tmp/say.mp3

**Comment by shivasiddharth** [comment] 2018-06-24 02:55
Please follow the issue template. This has already been discussed already. Duplicate of #204

**Closed by shivasiddharth** 2018-06-24 02:55 UTC
