### ISSUE TITLE
Voice Bonnet Audio Config

### ISSUE THREAD

**Issue by kevintee23** [shivasiddharth/GassistPi#467] opened 2018-08-02 11:03 UTC
Would like to find out if it is possible to get this running on the voice bonnet on the Google AIY V2 kit. If so, which audio configuration file do i use?

**Comment by shivasiddharth** [comment] 2018-08-02 11:05
Please search through the issues once, to check if any issues have been previously posted that may relate to yours. Duplicate of #444

**Closed by shivasiddharth** 2018-08-02 11:05 UTC
